// Generated by CoffeeScript 1.8.0
var CSON, auth, chalk, config, recipients, sms;

CSON = require('cson');

chalk = require('chalk');

sms = require('./lib/sms');

if ((process.argv[2] != null) && (process.argv[3] != null)) {
  config = CSON.parseFileSync("" + __dirname + "/config.cson");
  auth = config.auth;
  recipients = config.recipients;
  sms(auth, recipients, process.argv[2], process.argv.slice(3).join(" "));
} else {
  console.log(chalk.red("usage: sms <subject> <body>"));
}
