// Generated by CoffeeScript 1.8.0
var chalk, nodemailer, sms;

chalk = require('chalk');

nodemailer = require('nodemailer');

sms = function(auth, recipients, subject, body) {
  var message, transporter;
  this.auth = auth;
  this.recipients = recipients;
  this.subject = String(subject);
  this.body = String(body);
  message = {
    from: this.auth.user,
    to: this.recipients,
    subject: this.subject,
    text: this.body
  };
  transporter = nodemailer.createTransport({
    service: 'Gmail',
    auth: this.auth
  });
  return transporter.sendMail(message, function(error, info) {
    var status;
    status = error != null ? chalk.red("" + error.message) : chalk.green("Sent message(s). Got '" + info.response + "' from server.");
    return console.log(chalk.white("sms: " + status));
  });
};

module.exports = sms;
